import {
  AscensionSchema,
  BaseAttributeSchema,
  CharacterAttributeSchema,
  DestinedEquipmentSchema,
  EquipmentSchema,
  InventoryItemSchema,
  QuestSchema,
  SkillSchema,
} from './utils.ts';

export const Schema = z.object({
  世界: z.object({ 时间: z.string(), 地点: z.string() }),
  事件链: z
    .any()
    .prefault({})
    .transform(() => ({
      开启: z.boolean().prefault(false),
      结束: z.boolean().prefault(false),
      琥珀事件: z.boolean().prefault(false),
      标题: z.string(),
      阶段: z.string(),
      已完成事件: z.array(z.string()),
    })),
  任务列表: z.record(z.string(), QuestSchema),
  角色: z.object({
    种族: z.string(),
    身份: z.array(z.string()),
    职业: z.array(z.string()),
    生命层级: z.string().prefault('第一层级/普通层级'),
    等级: z.number().prefault(1),
    累计经验值: z.number(),
    升级所需经验: z.number().prefault(15),
    冒险者等级: z.string().prefault('未评级'),
    生命值上限: z.number(),
    生命值: z.number(),
    法力值上限: z.number(),
    法力值: z.number(),
    体力值上限: z.number(),
    体力值: z.number(),
    属性: CharacterAttributeSchema,
    技能列表: z.record(z.string(), SkillSchema),
  }),
  背包: z.record(z.string(), InventoryItemSchema),
  货币: z.object({
    金币: z.number().prefault(0),
    银币: z.number().prefault(0),
    铜币: z.number().prefault(0),
  }),
  装备: z.object({
    武器: z.record(z.string(), EquipmentSchema),
    防具: z.record(z.string(), EquipmentSchema),
    饰品: z.record(z.string(), EquipmentSchema),
  }),
  登神长阶: AscensionSchema,
  命定系统: z.object({
    命运点数: z.number(),
    命定之人: z.record(
      z.string(),
      z.object({
        是否在场: z.boolean().prefault(true),
        生命层级: z.string(),
        等级: z.number().prefault(1),
        种族: z.string(),
        身份: z.array(z.string()),
        职业: z.array(z.string()),
        性格: z.string(),
        喜爱: z.string(),
        外貌特质: z.string(),
        衣物装饰: z.string(),
        装备: z.record(z.string(), DestinedEquipmentSchema),
        属性: BaseAttributeSchema,
        登神长阶: AscensionSchema,
        是否缔结契约: z.boolean().prefault(false),
        好感度: z.number().prefault(0),
        评价: z.string(),
        背景故事: z.string(),
        技能: z.record(z.string(), SkillSchema),
      }),
    ),
  }),
  新闻: z.object({
    阿斯塔利亚快讯: z.object({
      势力要闻: z.string(),
      尊位行迹: z.string(),
      军事行动: z.string(),
      经济动脉: z.string(),
      灾害预警: z.string(),
    }),
    酒馆留言板: z.object({
      高额悬赏: z.string(),
      冒险发现: z.string(),
      怪物异动: z.string(),
      通缉要犯: z.string(),
      宝物传闻: z.string(),
    }),
    午后茶会: z.object({
      社交逸闻: z.string(),
      千里远望: z.string(),
      命运涟漪: z.string(),
      邂逅预兆: z.string(),
    }),
  }),
});
